import React from "react";

// next
import Head from "next/head";

// types
import type { NextPage } from "next";

const NextHead: NextPage = () => {
  return (
    <Head>
      <title>yanhauw.com</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default NextHead;
